### PR TITLE
Porting ui from widgets to QML

### PR DESCRIPTION
**Pull request by matteonistri**

### CODE REVIEW

**Review by guerinoni — CHANGES_REQUESTED** [review]
Looks good! :) 
A few thoughts
- Change commit messages with capital letter
- `if(human_turn && state == "empty")` this check should not stay in QML, maybe we can create a class for a game engine and a class that helps qml to handle and retrieve all info it need without put any login in it, we can separate later btw
- if assets grows or qml file grows we could also separate qrc file for assets only and qml only but for now it's ok ot keep them together

**Comment by matteonistri** [comment]
> if(human_turn && state == "empty") this check should not stay in QML, maybe we can create a class for a game engine and a class that helps qml to handle and retrieve all info it need without put any login in it, we can separate later btw.

About this point, I was thinking about exposing a method like `bool isMoveAllowed(quint8 cell)`, that internally checks wheter the cell is free and it is human's turn. What do you think?

**Comment by guerinoni** [comment]
@matteonistri yes with "game helper" I mean all property we need in order to keep QML stupid and all logic in C++ code for testing and better reuse of logic code and GUI code

**Review by guerinoni — APPROVED** [review]

**Comment by guerinoni** [comment]
Very good :)

**Pull request merged**
